name: e2e tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  test-setup-python:
    name: Test setup-python
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
          [
            windows-latest,
            ubuntu-22.04,
            ubuntu-22.04-arm,
            ubuntu-latest,
            ubuntu-24.04-arm,
            macos-latest,
            macos-13
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run with setup-python 3.9.13
        uses: ./
        with:
          python-version: 3.9.13
      - name: Verify 3.9.13
        run: python __tests__/verify-python.py 3.9.13

      - name: Run with setup-python 3.10.11
        uses: ./
        with:
          python-version: 3.10.11
      - name: Verify 3.10.11
        run: python __tests__/verify-python.py 3.10.11

      - name: Run with setup-python 3.11.9
        uses: ./
        with:
          python-version: 3.11.9
      - name: Verify 3.11.9
        run: python __tests__/verify-python.py 3.11.9

      - name: Run with setup-python 3.12.7
        uses: ./
        with:
          python-version: 3.12.7
      - name: Verify 3.12.7
        run: python __tests__/verify-python.py 3.12.7

      - name: Run with setup-python 3.13.0
        uses: ./
        with:
          python-version: 3.13.0
      - name: Verify 3.13.0
        run: python __tests__/verify-python.py 3.13.0

      - name: Run with setup-python 3.13
        id: cp313
        uses: ./
        with:
          python-version: '3.13'
      - name: Verify 3.13
        run: python __tests__/verify-python.py 3.13
      - name: Run python-path sample 3.13
        run: pipx run --python '${{ steps.cp313.outputs.python-path }}' nox --version

      - name: Run with setup-python ==3.13
        uses: ./
        with:
          python-version: '==3.13'
      - name: Verify ==3.13
        run: python __tests__/verify-python.py 3.13

      - name: Run with setup-python <3.13
        uses: ./
        with:
          python-version: '<3.13'
      - name: Verify <3.13
        run: python __tests__/verify-python.py 3.12

      - name: Test Raw Endpoint Access
        run: |
          curl -L https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json | jq empty
        shell: bash

 verify-install-path:
    name: Verify Install Path
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-11-arm]
        architecture: [x86, arm64]
        python-version: ['3.11', '3.12', '3.13.1', '3.14.0-beta.2']
        freethreaded: ['false']
        include:
          - os: windows-11-arm
            architecture: x86
            python-version: '3.13.1'
            freethreaded: true
          - os: windows-11-arm
            architecture: arm64
            python-version: '3.13.1'
            freethreaded: true
          - os: windows-11-arm
            architecture: x86
            python-version: '3.14.0-beta.2'
            freethreaded: true
          - os: windows-11-arm
            architecture: arm64
            python-version: '3.14.0-beta.2'
            freethreaded: true
          - os: windows-latest
            architecture: x86
            python-version: '3.10'
            freethreaded: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: ./
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
          freethreaded: ${{ matrix.freethreaded }}

      - name: Verify Install Path
        shell: pwsh
        run: python __tests__/verify-windows-install-path.py `
          ${{ matrix.python-version }} `
          ${{ matrix.architecture }} `
          ${{ matrix.freethreaded }}